### Todas las librerías que vamos a utilizar.

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from pathlib import Path
data_path = Path("../src")

### Guardamos la lectura del fichero en una variable.

In [4]:
dataset = Path(data_path / "AnnualCauseDeathNumbers.csv")
data = pd.read_csv(dataset)

### Ejemplo de los primeros archivos.

In [5]:
data.head()

,Entity,Code,Year,Meningitis fatalities,Dementia fatalities,Parkinson fatalities,Nutritional deficiency fatalities,Malaria fatalities,Drowning fatalities,Interpersonal violence fatalities,...,Chronic kidney fatalities,Poisoning fatalities,Protein energy malnutrition fatalities,Road injury fatalities,Chronic respiratory fatalities,Chronic liver fatalities,Digestive disease fatalities,Fire fatalities,Acute hepatitis fatalities,Measles fatalities
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,3709,338,2054,4154,5945,2673,5005,323,2985,10037
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,3724,351,2119,4472,6050,2728,5120,332,3092,10021
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,3776,386,2404,5106,6223,2830,5335,360,3325,9807
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,3862,425,2797,5681,6445,2943,5568,396,3601,10228
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,3932,451,3038,6001,6664,3027,5739,420,3816,12144

In [8]:
rd = data.sample(frac=0.15)
rd

,Entity,Code,Year,Meningitis fatalities,Dementia fatalities,Parkinson fatalities,Nutritional deficiency fatalities,Malaria fatalities,Drowning fatalities,Interpersonal violence fatalities,...,Chronic kidney fatalities,Poisoning fatalities,Protein energy malnutrition fatalities,Road injury fatalities,Chronic respiratory fatalities,Chronic liver fatalities,Digestive disease fatalities,Fire fatalities,Acute hepatitis fatalities,Measles fatalities
281,Armenia,ARM,2001,19,382,99,39,0,146,125,...,184,34,16,332,1078,552,933,85,5,0
2181,Gabon,GAB,2011,106,137,37,87,786,30,71,...,315,23,81,513,294,364,563,29,11,43
1700,Eastern Mediterranean Region who,wb,2010,39024,41614,11887,40374,16540,14283,31776,...,99331,7076,34181,145614,154700,121230,162575,13037,17531,24502
1587,Dominica,DMA,2017,1,19,6,2,0,4,8,...,42,1,2,12,22,11,25,2,0,0
4138,Nicaragua,NIC,2018,44,680,212,149,2,173,390,...,3421,22,147,736,1334,1607,2215,24,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Argentina,ARG,2010,558,10411,2544,1352,0,652,2452,...,13550,294,1284,6349,17202,6977,14748,717,35,0
3889,Morocco,MAR,2009,818,4031,940,270,0,522,452,...,6798,297,229,10313,7663,3659,6238,946,411,375
5708,Sudan,SDN,1998,2216,1731,462,3526,4807,2559,516,...,3063,965,3422,7140,7429,3637,5453,1883,3260,18934
6634,World Bank High Income,wb,1994,7266,310010,60635,10295,69,23433,41782,...,138851,6529,8224,184290,417718,207584,399896,16308,1268,1024
403,Bahamas,BHS,2003,4,36,10,5,0,24,62,...,64,1,5,44,33,44,83,10,0,0

### Algunas estadísticas de los archivos

In [9]:
rd.describe()

,Year,Meningitis fatalities,Dementia fatalities,Parkinson fatalities,Nutritional deficiency fatalities,Malaria fatalities,Drowning fatalities,Interpersonal violence fatalities,Maternal disorder fatalities,HIV/AIDS fatalities,...,Chronic kidney fatalities,Poisoning fatalities,Protein energy malnutrition fatalities,Road injury fatalities,Chronic respiratory fatalities,Chronic liver fatalities,Digestive disease fatalities,Fire fatalities,Acute hepatitis fatalities,Measles fatalities
count,1026.000000,1026.000000,1.026000e+03,1026.000000,1026.000000,1026.000000,1026.000000,1026.000000,1026.000000,1.026000e+03,...,1.026000e+03,1026.000000,1026.000000,1.026000e+03,1.026000e+03,1.026000e+03,1.026000e+03,1026.000000,1026.000000,1026.000000
mean,2004.601365,6653.787524,2.367635e+04,5536.323587,8601.461014,15520.704678,7215.810916,8497.704678,4815.406433,2.089009e+04,...,2.126235e+04,1780.028265,7506.500000,2.604979e+04,7.762842e+04,2.621266e+04,4.645087e+04,2383.616959,2375.295322,8048.728070
std,8.717348,29140.630013,9.703149e+04,21963.772553,37923.217924,82836.789778,31258.259288,34888.579552,21835.855347,1.169310e+05,...,8.236779e+04,7398.334326,32695.500492,1.012486e+05,3.249815e+05,1.009967e+05,1.768348e+05,9280.774346,11606.560710,40887.765686
min,1990.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
25%,1997.000000,16.000000,9.925000e+01,30.000000,11.000000,0.000000,31.000000,37.000000,6.000000,1.300000e+01,...,1.527500e+02,6.000000,6.000000,1.482500e+02,2.987500e+02,1.622500e+02,2.970000e+02,19.000000,2.000000,0.000000
50%,2004.000000,125.000000,8.100000e+02,206.500000,137.000000,0.000000,244.000000,308.500000,59.000000,1.720000e+02,...,1.136500e+03,66.500000,106.000000,1.243500e+03,2.091000e+03,1.466000e+03,2.627000e+03,149.000000,19.000000,2.000000
75%,2012.000000,1366.750000,4.248000e+03,984.750000,1726.250000,868.500000,934.000000,1191.000000,1144.750000,3.066000e+03,...,4.538000e+03,354.500000,1652.250000,5.482250e+03,7.959250e+03,5.143750e+03,9.047500e+03,566.000000,258.000000,420.000000
max,2019.000000,369377.000000,1.510447e+06,339540.000000,417494.000000,961129.000000,347930.000000,447514.000000,269609.000000,1.844490e+06,...,1.352271e+06,91491.000000,365960.000000,1.259242e+06,3.797538e+06,1.426787e+06,2.479463e+06,125826.000000,130208.000000,474584.000000